# Generated by Django 3.2.7 on 2021-10-15 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nuevoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.CharField(max_length=150)),
                ('Email', models.CharField(max_length=150)),
                ('pwd', models.CharField(max_length=150)),
                ('Edad', models.IntegerField()),
                ('Genero', models.CharField(max_length=1)),
                ('Estado', models.CharField(max_length=150)),
            ],
        ),
    ]
